# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bradford Geek
email: bradfordgeek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First template
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bradfordgeek.com" # the base hostname & protocol for your site
twitter_username: bradfordgeek
github_username:
instagram_username:  bradfordgeek

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
